name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies (composer if needed)
        run: |
          if [ -f composer.json ]; then composer install --no-interaction --prefer-dist; fi

      - name: Run PHP lint (syntax check)
        run: |
          set -e
          files=$(git ls-files '*.php')
          if [ -n "$files" ]; then php -l $files; fi

      - name: Run scripts in safe mode
        env:
          SKIP_NETWORK_PROBES: '1'
        run: |
          set -euo pipefail
          # Run quick, non-networking checks. Allow non-zero exit if scripts expect missing inputs.
          php -d memory_limit=512M scripts/precheck.php || true
          php -d memory_limit=1G sort.php || true
