name: Scheduled Generation

on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch: {}

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Prepare workspace
        run: |
          mkdir -p subscriptions/xray/base64 subscriptions/xray/normal subscriptions/singbox || true

      - name: Run generation scripts (safe mode)
        env:
          SKIP_NETWORK_PROBES: '1'
        run: |
          set -euo pipefail
          # Run the sorter and generator in safe-mode to avoid active network probes on GitHub runners.
          php -d memory_limit=1G sort.php || true
          php -d memory_limit=1G toSingbox.php || true

      - name: Upload generated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: psg-generated-subscriptions
          path: |
            subscriptions/**
            subscriptions/singbox/**
            subscriptions/nekobox/**
